<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Cdyl9vT' shared service.

return $this->privates['.service_locator.Cdyl9vT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'trackerManager' => ['privates', 'App\\Services\\TrackerManager', NULL, 'Cannot autowire service "App\\Services\\TrackerManager": argument "$em" of method "__construct()" references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to one of its parents: interface "Doctrine\\ORM\\EntityManagerInterface", or interface "Doctrine\\Common\\Persistence\\ObjectManager".'],
], [
    'trackerManager' => 'App\\Services\\TrackerManager',
]);
