<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\TrackerManager' shared autowired service.

include_once $this->targetDirs[3].'/vendor/coffeebike/owasys-bundle/Services/TrackerManager.php';
include_once $this->targetDirs[3].'/src/Services/TrackerManager.php';

return $this->privates['App\\Services\\TrackerManager'] = new \App\Services\TrackerManager();
