<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container75LkZ2L\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container75LkZ2L/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container75LkZ2L.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container75LkZ2L\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container75LkZ2L\srcApp_KernelProdContainer([
    'container.build_hash' => '75LkZ2L',
    'container.build_id' => 'c055b0f4',
    'container.build_time' => 1562788549,
], __DIR__.\DIRECTORY_SEPARATOR.'Container75LkZ2L');
