<?php

namespace Proxies\__CG__\CoffeeBike\OwasysBundle\Entity\Message;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MessageI extends \CoffeeBike\OwasysBundle\Entity\Message\MessageI implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'iox', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'ioType', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'ioVal', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'intsToSend', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'intsElapsed', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'intsTotal'];
        }

        return ['__isInitialized__', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'iox', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'ioType', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'ioVal', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'intsToSend', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'intsElapsed', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageI' . "\0" . 'intsTotal'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MessageI $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIox($iox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIox', [$iox]);

        return parent::setIox($iox);
    }

    /**
     * {@inheritDoc}
     */
    public function getIox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIox', []);

        return parent::getIox();
    }

    /**
     * {@inheritDoc}
     */
    public function setIoType($ioType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIoType', [$ioType]);

        return parent::setIoType($ioType);
    }

    /**
     * {@inheritDoc}
     */
    public function getIoType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIoType', []);

        return parent::getIoType();
    }

    /**
     * {@inheritDoc}
     */
    public function setIoVal($ioVal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIoVal', [$ioVal]);

        return parent::setIoVal($ioVal);
    }

    /**
     * {@inheritDoc}
     */
    public function getIoVal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIoVal', []);

        return parent::getIoVal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntsToSend($intsToSend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntsToSend', [$intsToSend]);

        return parent::setIntsToSend($intsToSend);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntsToSend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntsToSend', []);

        return parent::getIntsToSend();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntsElapsed($intsElapsed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntsElapsed', [$intsElapsed]);

        return parent::setIntsElapsed($intsElapsed);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntsElapsed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntsElapsed', []);

        return parent::getIntsElapsed();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntsTotal($intsTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntsTotal', [$intsTotal]);

        return parent::setIntsTotal($intsTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntsTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntsTotal', []);

        return parent::getIntsTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriggerSource($triggerSource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriggerSource', [$triggerSource]);

        return parent::setTriggerSource($triggerSource);
    }

    /**
     * {@inheritDoc}
     */
    public function getTriggerSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTriggerSource', []);

        return parent::getTriggerSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp($timestamp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', [$timestamp]);

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', []);

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTracker(\CoffeeBike\OwasysBundle\Entity\Tracker $tracker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTracker', [$tracker]);

        return parent::setTracker($tracker);
    }

    /**
     * {@inheritDoc}
     */
    public function getTracker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTracker', []);

        return parent::getTracker();
    }

}
