<?php

namespace Proxies\__CG__\CoffeeBike\OwasysBundle\Entity\Message;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MessageG extends \CoffeeBike\OwasysBundle\Entity\Message\MessageG implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'outOfGeofence', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'geofenceLat', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'geofenceLon', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'currentLat', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'currentLon'];
        }

        return ['__isInitialized__', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'outOfGeofence', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'geofenceLat', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'geofenceLon', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'currentLat', '' . "\0" . 'CoffeeBike\\OwasysBundle\\Entity\\Message\\MessageG' . "\0" . 'currentLon'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MessageG $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setOutOfGeofence($outOfGeofence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutOfGeofence', [$outOfGeofence]);

        return parent::setOutOfGeofence($outOfGeofence);
    }

    /**
     * {@inheritDoc}
     */
    public function getOutOfGeofence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutOfGeofence', []);

        return parent::getOutOfGeofence();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeofenceLat($geofenceLat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeofenceLat', [$geofenceLat]);

        return parent::setGeofenceLat($geofenceLat);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeofenceLat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeofenceLat', []);

        return parent::getGeofenceLat();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeofenceLon($geofenceLon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeofenceLon', [$geofenceLon]);

        return parent::setGeofenceLon($geofenceLon);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeofenceLon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeofenceLon', []);

        return parent::getGeofenceLon();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentLat($currentLat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentLat', [$currentLat]);

        return parent::setCurrentLat($currentLat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentLat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentLat', []);

        return parent::getCurrentLat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentLon($currentLon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentLon', [$currentLon]);

        return parent::setCurrentLon($currentLon);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentLon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentLon', []);

        return parent::getCurrentLon();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriggerSource($triggerSource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriggerSource', [$triggerSource]);

        return parent::setTriggerSource($triggerSource);
    }

    /**
     * {@inheritDoc}
     */
    public function getTriggerSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTriggerSource', []);

        return parent::getTriggerSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp($timestamp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', [$timestamp]);

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', []);

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTracker(\CoffeeBike\OwasysBundle\Entity\Tracker $tracker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTracker', [$tracker]);

        return parent::setTracker($tracker);
    }

    /**
     * {@inheritDoc}
     */
    public function getTracker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTracker', []);

        return parent::getTracker();
    }

}
