<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XLOeg.F' shared service.

return $this->privates['.service_locator.XLOeg.F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\StoreController::store' => ['privates', '.service_locator.Cdyl9vT', 'get_ServiceLocator_Cdyl9vTService.php', true],
    'App\\Controller\\StoreController:store' => ['privates', '.service_locator.Cdyl9vT', 'get_ServiceLocator_Cdyl9vTService.php', true],
], [
    'App\\Controller\\StoreController::store' => '?',
    'App\\Controller\\StoreController:store' => '?',
]);
